ALTER TABLE customers ADD COLUMN IF NOT EXISTS odoo_id VARCHAR(100);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS odoo_id VARCHAR(100);
ALTER TABLE invoice_payments ADD COLUMN IF NOT EXISTS odoo_id VARCHAR(100);
